version: '3.8'
services:
  gradebook:
    build:
      context: .
      target: development
    ports:
      - '8000:8000'
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/gradebook
    volumes:
      - ./:/app

  mysqlserver:
    image: mysql:8.0.23
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=gradebookuser
      - MYSQL_PASSWORD=gradebook
      - MYSQL_DATABASE=gradebook
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:
